#pragma once

#include "System.Array.h"
#include "System.Array.hpp"
#include "System.BitConverter.h"
#include "System.Buffer.h"
#include "System.Char.h"
#include "System.Convert.h"
#include "System.Environment.h"
#include "System.Exception.h"
#include "System.IComparable.h"
#include "System.IEquatable.h"
#include "System.IFormatProvider.h"
#include "System.Int32.h"
#include "System.Int64.h"
#include "System.Math.h"
// (hidden) #include "System.NumberFormatter.h"
#include "System.Object.h"
#include "System.Ownership.h"
#include "System.Single.h"
#include "System.String.h"
#include "System.UInt32.h"
